# File Tree: Multi_Agent

**Generated:** 3/17/2026, 8:46:04 AM
**Root Path:** `c:\Users\user\Desktop\crm_chatbot2\Multi_Agent`

```
├── 📁 config
│   └── 🐍 settings.py
├── 📁 data
│   ├── 📁 processed
│   └── 📁 raw
│       └── 📕 support_faq_fr_test.pdf
├── 📁 src
│   ├── 📁 agents
│   │   ├── 🐍 __init__.py
│   │   ├── 🐍 confidence_agent.py
│   │   ├── 🐍 llm_agent.py
│   │   ├── 🐍 rag_agent.py
│   │   ├── 🐍 rewriter_agent.py
│   │   └── 🐍 router_agent.py
│   ├── 📁 api
│   │   ├── 🐍 __init__.py
│   │   └── 🐍 main.py
│   ├── 📁 graph
│   │   ├── 🐍 __init__.py
│   │   └── 🐍 workflow.py
│   ├── 📁 ingestion
│   │   ├── 🐍 __init__.py
│   │   ├── 🐍 embedder.py
│   │   ├── 🐍 loader.py
│   │   ├── 🐍 pipeline.py
│   │   └── 🐍 splitter.py
│   ├── 📁 ui
│   │   ├── 🐍 __init__.py
│   │   └── 🐍 app.py
│   └── 🐍 __init__.py
├── 🐍 debug_scores.py
├── 📄 requirements.txt
└── 🐍 reset_collection.py
```

---

_Generated by FileTree Pro Extension_
